### ISSUE TITLE
当使用docker compose部署时，添加HEADSCRIPT变量后，貌似会缺一个`}`

### ISSUE THREAD

**Issue by nixingshiguang** [babaohuang/GeminiProChat#171]
### How is Gemini Pro Chat deployed?

Docker

### Describe the bug

使用docker compose部署，yaml文件如下：
```yml
version: "3.3"
services:
  geminiprochat:
    container_name: geminiprochat
    restart: always
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    environment:
      HEAD_SCRIPTS=<script src="https://excample.com/custom.js" defer ></script>
      #HEAD_SCRIPTS="<script src=\"https://excample.com/custom.js\" defer ></script>"
    image: babaohuang/geminiprochat:latest
networks: {}
```

试过用`"`包裹起来，也试过使用`\`转义src中的双引号，但是结果都会造成以下问题

### Console Logs

日志：
```
Starting service...
Running script...
Server listening on http://0.0.0.0:3000
03:32:18 AM [ssr] SyntaxError: Missing } in template expression
    at ESMLoader.moduleStrategy (node:internal/modules/esm/translators:119:18)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:468:14)
    at async link (node:internal/modules/esm/module_job:68:21)
```

### Participation

- [ ] I am willing to submit a pull request for this issue.
